apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis
  namespace: flaskapp-dev
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - name: redisport
          containerPort: 6379
