version: '3'
services:
        web:
                image: rohit021191/composeapp
                command: python app.py
                ports:
                        - "5000:5000"
                volumes:
                        - .:/composeapp
        redis:
                image: redis

