---
services:
  registry:
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    image: "registry:2"
    ports:
      - "5000:5000"
    volumes:
      - "./data:/data"
      
version: "3"
